### ISSUE TITLE
Populate URIs for TimestampVerificationResult

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#193]
**Description**

Currently, the URIs for `TimestampVerificationResult` structs are not populated on verification - [1](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/signed_entity.go#L625), [2](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/signed_entity.go#L650), [3](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/signed_entity.go#L677), [4](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/signed_entity.go#L688-L693).

In order to implement this, we would need to plumb through the trust material, particularly the URI, from the verifier for each verified timestamp.

cc @phillmv

**Comment by cmurphy** [comment]
For the [first instance](https://github.com/sigstore/sigstore-go/blob/d19dc5bd33f20e43bf49eaafcaeded0173c6b526/pkg/verify/signed_entity.go#L670) - the verification result comes from the transparency log, which [does not have a URI](https://github.com/sigstore/protobuf-specs/blob/0606c22cb98424a7c6ebcee3ffe0a55dda9c35c5/protos/sigstore_trustroot.proto#L33-L63) in the trusted root. What value do you expect for the URI here? `baseUrl`?

For the [last instance](https://github.com/sigstore/sigstore-go/blob/d19dc5bd33f20e43bf49eaafcaeded0173c6b526/pkg/verify/signed_entity.go#L733-L738) it doesn't look like this is a verification result, just a transfer of data from the leaf certificate to the result struct. Should the URI be inferred from the issuing certificate authority?

For the other timestamp authority instances, the production trusted_root.json [does not include a URI for the timestamp authorities](https://github.com/sigstore/root-signing/blob/85aba600104e996f4517a076e1b0e268d3ded969/targets/trusted_root.json#L90-L113), so most users viewing this verification result would get an empty string here, is that what you're wanting?

**Comment by cmurphy** [comment]
Partial implementation minus the unanswered questions https://github.com/sigstore/sigstore-go/pull/270

**Comment by Hayden-IO** [comment]
As a meta comment, I'm not sure how we expect URI to be used. If this is just for logging purposes, then best effort population of the URI seems sufficient.

For the first instance, yea, [base_url](https://github.com/sigstore/protobuf-specs/blob/0606c22cb98424a7c6ebcee3ffe0a55dda9c35c5/protos/sigstore_trustroot.proto#L35) should be the correct value.

For the last instance, this looks incorrect, you shouldn't be verifying a certificate with its own timestamp, that would always verify.\
As for the URI, I guess empty would be fine since there is no URI.

For the TSA, yea you're right. I think this came up once before as a blocker, that there is no way to tie a verifier back to its issuing TSA since that URI is only given on signing.

With all this said...Taking a step back, do you think URI is useful? Is there something else we can provide to note the timestamp's source?

**Comment by cmurphy** [comment]
> With all this said...Taking a step back, do you think URI is useful?

I could imagine someone creating a policy that checked the URI in the verification result.

> Is there something else we can provide to note the timestamp's source?

Maybe we could use the [subject](https://github.com/sigstore/root-signing/blob/85aba600104e996f4517a076e1b0e268d3ded969/targets/trusted_root.json#L92-L95) in the TSA leaf cert?

> there is no way to tie a verifier back to its issuing TSA since that URI is only given on signing.

I may be misunderstanding, but I think it is possible to use the URI as long as it is given in a private [trusted_root.json](https://github.com/sigstore/protobuf-specs/blob/0606c22cb98424a7c6ebcee3ffe0a55dda9c35c5/protos/sigstore_trustroot.proto#L77). I was just noting that it doesn't happen to be given in the p-g-i trusted_root.json. Maybe we could change that?

**Comment by Hayden-IO** [comment]
> I could imagine someone creating a policy that checked the URI in the verification result.

I think this would be OK, though I'd rather see policies around only around cryptographic keys. A URI seems more like human-readable output.

> Maybe we could use the [subject](https://github.com/sigstore/root-signing/blob/85aba600104e996f4517a076e1b0e268d3ded969/targets/trusted_root.json#L92-L95) in the TSA leaf cert?

That seems good! 

> I may be misunderstanding, but I think it is possible to use the URI as long as it is given in a private [trusted_root.json](https://github.com/sigstore/protobuf-specs/blob/0606c22cb98424a7c6ebcee3ffe0a55dda9c35c5/protos/sigstore_trustroot.proto#L77). I was just noting that it doesn't happen to be given in the p-g-i trusted_root.json. Maybe we could change that?

Ah you're right, missed that. Yes, we should encourage URI to be included. We're actually removing GitHub's TSA from the [trust root](https://github.com/sigstore/root-signing/issues/1268), but I think it'd be sufficient to assume that the provided trust root would include a URI (fyi @kommendorkapten, for the trust root GitHub ships)

**Comment by kommendorkapten** [comment]
The TSA in sigstore targets is about to be removed as @haydentherapper mentioned. But the TSA _should_ contain an URI. GitHub's [trusted root](https://tuf-repo.github.com/targets/2937dca31a74e77d6cd2eed75c5cf1d89e0f7458d22faff1ebe9e7bc5860c2a5.trusted_root.json) contains the URI. I think the reason the Sigstore one does not contain is because we added it prior to the service was deployed, and we never went on to actually update it. 

As @haydentherapper said, `base_url` for the tlog is what to use. 

A general note on storing the URI in the verification result is more a nice to have, I'm not sure about any concrete use-cases. As the general approach to verify is to first provide the trust root, i.e the trusted set of TSAs, this means that _if_ verification succeeds, it's verified against _your trusted TSAs_. So there is no real need to actually have a second policy against the verification result, as they only contain trusted TSAs. That said, there could be cases for such a policy, but I just can't think of it right now. But during verification it's nice to provide that list to the user:

```
verification successful, verified against:
* transparency log rekor.sigstore.dev
* TSA timestamp.foo.com
etc eetc
```

I.e. see the URI more for informational purposes as of now.
