### ISSUE TITLE
Positioning sigstore-go vs other Sigstore libraries

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#29]
I'd like to discuss what libraries are authoritative for verification logic throughout the Sigstore stack. I've thought about sigstore-go as glue for services. Ideally, I would like the following (and this is just my thoughts!):

* Rekor libraries
   * Type construction and parsing
   * Rekor client
   * Inclusion/consistency proof verification (if we need to simplify the existing trillian/transparency-dev APIs, otherwise use those directly)
* Fulcio libraries
   * Short-lived certificate verification (FWIW, this is fairly lightweight which is why we see it duplicated in each implementation currently)
   * Fulcio gRPC/HTTP clients
* Timestamp libraries
   * RFC3161 timestamp verification 
* sigstore-go
   * Bundle consumption & generation
   * Golang logic for "code signing and transparency"
      * Glue between Signature/Attestation, Certificate/Key, Timestamp, and Inclusion Proof
      * Certificate could be Fulcio, could be self-managed PKI, etc. Timestamp could be from a TSA, SET, etc. These are higher-level concepts that represent the building blocks for transparent signing.
      * Designed such that we can support both the expected Sigstore path and other signing/verification flows 
* sigstore/sigstore
   * Shared between Sigstore services and Golang clients (sigstore-go, gitsign)
   * Maybe should get folded into sigstore-go, but circular dependencies can occur

I'd like to align on this, as it'll drive what the dependency tree should look like and how we can simplify it.

Previous discussion around this: https://github.com/sigstore/sigstore/issues/678

_Originally posted by @haydentherapper in https://github.com/sigstore/sigstore-go/issues/28#issuecomment-1804711890_

**Comment by kommendorkapten** [comment]
I support this proposal!

**Comment by kommendorkapten** [comment]
A question that come up, where would we think code that interacts with an OCI registry should live? sigstore/sigstore?

It would be needed by e.g. cosign to sign and publish images, but also on the verification side.
sigstore-go today only verifies a bundle, but it's easy to convert existing cosign signatures to a bundle that sigstore-go could verify.

A helper function to convert the data from the registry to a bundle should probably live in sigstore-go, but the logic that fetches all the signature (and Rekor entry) should probably be in sigstore/sigstore?

**Comment by Hayden-IO** [comment]
Cosign - It provides APIs to sign and verify containers. Same as gitsign, the core logic lives in sigstore/sigstore-go while gitsign handles signing commits. This keeps sigstore-go slim and Cosign remains larger.

Cosign can also provide APIs to transform between sigstore-go structs and OCI structs.

**Comment by Hayden-IO** [comment]
Going to close this since I'm not sure there's more to discuss at this point, though maybe it's worth putting this into a doc long-term.
