### ISSUE TITLE
Add unit tests for online log verification and inclusion proofs

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#53]
**Description**

The mock Sigstore data generates a Rekor log entry with a SignedEntryTimestamp but no inclusion proof (See [`generateTlogEntry`](https://github.com/sigstore/sigstore-go/blob/9a59c7f51a05d2305a8ba4ab9343416aaaeb16d6/pkg/testing/ca/ca.go#L248)).

Additionally, we don't test the online verification path since we don't have a fake Rekor client. Should be straightforward to add with something like https://github.com/sigstore/rekor-monitor/blob/main/pkg/rekor/mock/mock_rekor_client.go

**Comment by Hayden-IO** [comment]
Additionally, we should either add unit tests for https://github.com/sigstore/sigstore-go/blob/main/pkg/tlog/entry.go or confirm that the unit/integration tests for https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/tlog.go cover entry.go

**Comment by cmurphy** [comment]
@vishal-chdhry are you still interested in [taking this up](https://github.com/sigstore/sigstore-go/pull/188#issuecomment-2149435433) or should someone else have a go?

**Comment by vishal-chdhry** [comment]
@cmurphy sure I can take this up, I forgot about it

**Comment by vishal-chdhry** [comment]
\assign
