### ISSUE TITLE
Support additional GeneralNames in the SubjectAlternativeName

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#55]
**Description**

See https://github.com/sigstore/sigstore-go/blob/main/pkg/fulcio/certificate/summarize.go#L64

- [ ] Support OtherName, used by Fulcio for user names in certificates (not currently in use in production)
- [ ] Support parsing additional GeneralNames like DNS, for BYO PKI use cases

**Comment by cmurphy** [comment]
https://github.com/sigstore/sigstore-go/pull/229 adds support for parsing OtherName in fulcio certificates.

The function linked is only used for parsing Fulcio certificates, and I don't think Fulcio can issue certificates with other GeneralNames as SANs: https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md

Does sigstore-go support "BYO PKI"? I'm wondering if the second bullet point needs to be completed if there's not yet an identifiable use case, or if we could elaborate on the expected workflow for a DNS-type identity.
