### ISSUE TITLE
Changing VerificationContent interface method to return certificate by pointer

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#75]
**Description**

[`HasCertificate`](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/interface.go#L67) returns a certificate by value along with a boolean to denote if the certificate was returned. A proposed simplification of this interface would be to change it to `Certificate() (*x509.Certificate)`, which has two benefits: Passing by pointer over copy to avoid copying potentially large certificates, and removing the need to return a boolean when you can simply check if the return value is not nil.

One question for the original implementers: Was this function named to mirror the other function that returns an interface and boolean, since we can't return an interface by pointer?

**Comment by steiza** [comment]
> One question for the original implementers: Was this function named to mirror the other function that returns an interface and boolean, since we can't return an interface by pointer?

I think so, along with things like `HasInclusionPromise()` and `HasInclusionProof()` where we just return a `bool`. But I don't think we depend on this naming / consistency, and this proposed change sound fine to me.
