### ISSUE TITLE
Change online flag behavior to only fallback

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#80]
**Description**

Bundles are required to have inclusion proofs. The only time online verification would be needed is for API callers who are providing verification material without a bundle and without an inclusion proof/SET.

Online verification provides the same security guarantees as offline verification, for offline or online verification (wrote up details in https://github.com/stacklok/minder/pull/2120#issuecomment-1892619405), except with the added latency and decreased privacy (since you're identifying what artifact hash or identity you're verifying to the log).

**I would like to change the behavior of the online flag to fallback to querying Rekor only if an inclusion proof/SET was not successfully verified.**

Long-term, I would like to remove online verification entirely and require an inclusion proof to be presented. This somewhat relates to https://github.com/sigstore/sigstore-conformance/issues/122, standardizing on the bundle as input. However this isn't pressing to do immediately, and this would require updating the client spec to remove online verification.

**Comment by steiza** [comment]
At the sigstore-go client meeting, we said that alternatively we could just remove the online lookup option.

**Comment by Hayden-IO** [comment]
@steiza Good to close?
