### ISSUE TITLE
Standardize naming of insecure/unsafe functions

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#81]
**Description**

We have a few policy-level configuration functions that allow for insecure verification, useful for testing or private deployments: `WithoutAnyObserverTimestampsInsecure`, `WithoutIdentitiesUnsafe`, `WithoutArtifactUnsafe`. We should pick either "insecure", "unsafe", or some other adjective to describe risky verification behavior.

**Comment by phillmv** [comment]
Just to repeat what I wrote in the slack:

I feel a preference for `Unsafe` over `Insecure` in so are that the first one implies "use with caution" and the other implies "inherently bad".

(Tho having typed that out, there is a qualitative difference in these options, isn't there? To try to just validate the bundle absent the artifact is one thing; the integrity of the Sigstore "system" is not at stake. Whereas to verify without ANY observer timestamps does imply that we're doing something other than the default Sigstore path)
