### ISSUE TITLE
Pluralize WithTransparencyLog function name

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go#85]
**Description**

All other policy functions are pluralized. Should we pluralized WithTransparencyLog too? Might also want to update this to `WithRekorLogs` pending the discussion in https://github.com/sigstore/sigstore-go/issues/71.

**Comment by cmurphy** [comment]
I'm not sure I agree this should be plural - the log is singular, log entries are plural. It's also not true that all the other policy functions are plural:

https://github.com/sigstore/sigstore-go/blob/8353276693410dbcce73333163c2bdaffebb50ee/pkg/verify/signed_entity.go#L112
https://github.com/sigstore/sigstore-go/blob/8353276693410dbcce73333163c2bdaffebb50ee/pkg/verify/signed_entity.go#L363
https://github.com/sigstore/sigstore-go/blob/8353276693410dbcce73333163c2bdaffebb50ee/pkg/verify/signed_entity.go#L405
https://github.com/sigstore/sigstore-go/blob/8353276693410dbcce73333163c2bdaffebb50ee/pkg/verify/signed_entity.go#L430

**Comment by steiza** [comment]
I don't have a strong opinion here, which is probably a vote for leaving things as they are.

**Comment by Hayden-IO** [comment]
The policy functions that set thresholds are pluralized - https://github.com/sigstore/sigstore-go/blob/8353276693410dbcce73333163c2bdaffebb50ee/pkg/verify/signed_entity.go#L119-L187

With that said, I'm not super opinionated on this, and am fine to leave this as-is if we want to avoid one less breaking change for not much benefit.
